// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwFsLOCvEJ7-SjQUeQKU2UG9UY8QqcQvo',
    appId: '1:560817759937:web:702617af8db800c2cc9640',
    messagingSenderId: '560817759937',
    projectId: 'busticketbooking-dee4c',
    authDomain: 'busticketbooking-dee4c.firebaseapp.com',
    storageBucket: 'busticketbooking-dee4c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA02_s4FctDuomB7D9FHW2RBsOmXzYl5hU',
    appId: '1:560817759937:android:980fe65731243908cc9640',
    messagingSenderId: '560817759937',
    projectId: 'busticketbooking-dee4c',
    storageBucket: 'busticketbooking-dee4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhHm7PIvkQ3e9g0PmIRcHK-pAovACmHow',
    appId: '1:560817759937:ios:87d0c251a2d9fc43cc9640',
    messagingSenderId: '560817759937',
    projectId: 'busticketbooking-dee4c',
    storageBucket: 'busticketbooking-dee4c.appspot.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhHm7PIvkQ3e9g0PmIRcHK-pAovACmHow',
    appId: '1:560817759937:ios:6f4a37e97a1d0937cc9640',
    messagingSenderId: '560817759937',
    projectId: 'busticketbooking-dee4c',
    storageBucket: 'busticketbooking-dee4c.appspot.com',
    iosBundleId: 'com.example.demo.RunnerTests',
  );
}
